Tree iterator pull req.
medicalml/uav-forests pull request #7
Opened 2020-01-25 15:57 UTC by MaczekO

Tree iterator module, for iterating over shapes in "obszar_[nazwa].shp" files.

Iterator usage:
```
from forest_iterator_class import ForestIterator
iterator = ForestIterator(rgb_tif_path, shapes_shp_path, nir_tif_path)
```

You can then iterate over the shapes in the file. If the NIR file has been provided the iterator will also reshape it and create NDVI map of the region.

Each iteration yields dictionary with keys "rgb" and "description" (if NIR is provided there is also "ndvi" key).
* 'rgb' - masked numpy array of the area with given index
* 'ndvi' - masked numpy array of the NDVI area with given index
* 'description' - additional information provided about each segment of the forest in shp file

2020-01-25 16:54 UTC, mkosturek requested changes
Dodatkowo - przenieść cały skrypt do odpowiedniego folderu w strukturze  src/orthophotomap

2020-01-25 16:54 UTC, mkosturek commented on src/forest_iterator_class.py
> +def initiate_geoms(shp):
Proponuję dodać typizację argumentu, bo tutaj nie wiem czym jest shp - słownikiem czy czymś innym?
Czyli np.
`def initiate_geoms(shp: dict):...`

2020-01-25 16:54 UTC, mkosturek commented on src/forest_iterator_class.py
> +        win = rasterio.windows.Window.from_slices((row_stop, row_start), (col_start, col_stop))
Zastanawia mnie kolejność `(row_stop, row_start)`...

2020-01-25 16:54 UTC, mkosturek commented on src/forest_iterator_class.py
> +        img = np.stack([self.rgb_tif_handler.read(i + 1, window=win) for i in range(3)])
2 rzeczy:

1) stack sprawi że obraz będzie miał shape (channels, H, W), a raczej częściej używane jest (H,W,C). Może dodać gdzieś konwersję albo parametr którym można wybrać czy konwersja ma być robiona czy nie.

2) Można też po prostu odczytać na raz wszystkie kanały
```python
img = self.rgb_tif_handler.read(window=win).transpose(1,2,0)[:,:,:3]
```
Ewentualnie dodać gdzieś do klasy argument `alpha_channel: bool`, i wtedy mieć np tak:
```python
img = self.rgb_tif_handler.read(window=win).transpose(1,2,0)[:,:,:3 + selg.alpha_channel]
```
Oczywiście wywołanie transpose jeśli chcemy mieć shape (H,W,C) bez tego jest (C, H, W)

2020-01-25 16:54 UTC, mkosturek commented on src/forest_iterator_class.py
> +        ndvi = np.float32(ndvi)
1) Samo liczenie NDVI (linijki 43-45) wydzieliłbym do osobnego skryptu gdzieś w utils.
2) Całą metodę `create_ndvi` przerobiłbym na coś w rodzaju metody apply on image, która może przyjąć jako argument metodę przeliczającą coś na numpyowych arrayach - taki raczej luźny pomysł

2020-01-26 01:35 UTC, MaczekO commented on src/utils/infrared.py
> +    red_img_norm = red_channel_img / np.max(red_channel_img)
W sumie tutaj można zmienić na 255 albo 1 w zależności od typu red_channel_img, żeby zachować informację o natężeniu czerwieni

2020-01-26 01:37 UTC, CMataczynski reviewed
Dorzuciłem jeden komentarz, ale teraz już nie będę zmieniał.

2020-01-26 11:30 UTC, mkosturek commented on src/utils/infrared.py
> +    red_img_norm = red_channel_img / np.max(red_channel_img)
Tzn. zamiast dzielenia przez `max` podzielić przez 255 (albo przez 1.0), tak?

2020-01-26 19:58 UTC, mkosturek approved these changes

2020-01-26 19:58 UTC, merged